import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ViewTransitions from "@/components/motion/ViewTransitions";
import StoreProvider from "@/components/providers/StoreProvider";
import "../styles/globals.css";
import "../styles/shaders.css";
import "../styles/animation.css";
import "../styles/components/card.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <ViewTransitions />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
